ACK_TIMEOUT = 2
ACK_RANDOM_FACTOR = 1.5
MAX_RETRANSMIT = 4
MAX_RETRANSMISSION_SPAN = (ACK_TIMEOUT * ((2 ** MAX_RETRANSMIT) - 1) * ACK_RANDOM_FACTOR)
MAX_RETRANSMISSION_WAIT = (ACK_TIMEOUT * ((2 ** (MAX_RETRANSMIT + 1)) - 1) * ACK_RANDOM_FACTOR)
COAP_CONCURRENT_TRANSACTIONS = 1000
